version: 0.2
phases:
    pre_build:
        commands:
            - echo Prepare the building environment
            - apk --no-cache add --virtual builds-deps libc6-compat
    build:
        commands:
            - echo Building the app...
            - yarn install --network-timeout 300000 --frozen-lockfile
            - yarn build
artifacts:
    files:
        - ./package.json
        - ./yarn.lock
        - ./build/**/*
        - ./server/**/*
        - ./scripts/*
        - ./appspec.yml
        - ./release
    discard-paths: no
