#!/bin/bash

if [ "$APPLICATION_NAME" == "crowdserve-dev" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-admin" ]; then
    rm -rf ./.env
    yarn install --prod --frozen-lockfile --cache-folder /mnt/ycache --network-timeout 300000
    rm -f index.js && cp server/index.js . && rm -rf server
fi

if [ "$APPLICATION_NAME" == "crowdserve-prod" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-admin" ]; then
    aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 423361175163.dkr.ecr.ap-southeast-1.amazonaws.com

    docker pull 423361175163.dkr.ecr.ap-southeast-1.amazonaws.com/crowdserve-frontend-admin
fi