#!/bin/bash

if [ "$APPLICATION_NAME" == "crowdserve-dev" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-admin" ]; then
    pm2 start crowdserve-frontend-admin
fi

if [ "$APPLICATION_NAME" == "crowdserve-prod" ] && [ "$DEPLOYMENT_GROUP_NAME" == "crowdserve-frontend-admin" ]; then
    docker run -d --restart=always \
        --name=crowdserve-frontend-admin \
        --network=crowdserve-prod \
        -p 8081:8081 \
        -e NODE_ENV="production" \
        -e PORT=8081 \
        423361175163.dkr.ecr.ap-southeast-1.amazonaws.com/crowdserve-frontend-admin
fi