export const UserRoutes = {
  dashboard: '/dashboard',
  dashboardSaas: '/saas',
  home: '/',
  forms: {
    colors: '/forms-colors',
    elements: '/forms-elements',
    layouts: '/forms-layouts',
    validation: '/forms-validation',
    upload: '/forms-upload',
    wizard: '/forms-wizard',
  },
  tablesBasic: '/tables-basic',
  tablesResponsive: '/tables-responsive',
  tablesControlColumn: '/tables-control-column',
  uielements: {
    uiAlerts: '/ui-alerts',
    uiCards: '/ui-cards',
    uiProgress: '/ui-progress',
    uiTypography: '/ui-typography',
    uiRates: '/ui-rates',
    uiNotification: '/ui-notification',
  },
  events: '/events',
  createEvent: '/create-event',
  eventDetail: '/event-detail/:id',
  users: '/users',
  userDetail: '/user/:userId',
  userTicketDetail: '/user-ticket-detail/:ticketId',
  tickets: '/tickets',
  settings: '/settings',
  ticketDetail: '/ticket-detail/:ticketId',
  eventInfo: '/event-info/:id',
  eventTickets: '/event-tickets/:id',
  eventTicketsDetail: '/event-tickets-detail/:eventId/:ticketId',
  transactions: '/transactions',
  transactionsDetail: '/transactions-detail/:transactionsId',
};

export const AuthRoutes = {
  login: '/login',
  register: '/register',
};
